# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "o5YDUcQeZvAy1I7UYv5SZ7JJpsQYav9wAEfD/wmHRTsuPBnzHab0G8eLM/utMSc2yPUDYGL5eS5yU4/wJe5lzIaUGN4L3tyC0ekaIuX27W1+v7Olk7QdTS/qSA3Jix/XqzjnwwUSMS43nAJhugRGQLvETljhuZen6QcbCPB+gL9LgRUzBjaCdWMvoeg2wbgRnfSWtjunNKUpnNXK/q+l4je8qPXPLHBEgGdeYeHKymiH/MEutnnEZ110JZuMs8KIJGUtZ/dWImNGVe0sZq78/aDGiUGdwmWxb49hqDpPxVeGILNyxYahcFzJHNpZlFRXvbFoc/wlfXFYBAhv5R27nNR4z1shL77cOIzMhRekXiWggANgCop70KEXgPulxyPGAxFM+/2hohVmyNhm3ITaKZPOvZJAB64FVn7UmabHu/mz78eMFcz/x3eRPz7ANBJYW+c6WXv1k7Hju6NDaXduuvN2lVPTroOLIYxniV+vealLgvEmq1PUltCHhxSqAyb+7CSrHIqmmAWzilxXa+C5aGSLpv7Je03ycU04qLRjpN16oCU36EjVJJjzfEd0CdSfGkuAiKhGF105Gj4DUPXoIUr8EaoJd1yLsYVDYK/thYRwpwFNBh6t8BSBI0Ka9grXusxV4/F7VRrkY8KmzEmjyk1jRkY7AOMMUCqJ+iJL2H4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
