appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iPfUiufhs18b4LSkZpiJC/Hd5rimwVAveDIEBlavdClzrioRbcmA2OXD25+Id0hg18YsgEBA4gaE0H6W4rSYFhLvAeaujX6BfENbYLKLQ3PYC8L1h9M0oFwPTGMn0XzPZHRXiRy0RLki6Zs2ONxIOQWx13jNZLxM4xHk15YTIf9ZLXfLMaL4ogvJr1SF3N9AQUBLfL7t58VpdmbJMf/9D+o+9vpUvXHejgd9NQ8W1cZ1OvojO/EkzbZiO/YL8MioLKPr+a+djIcX5zLYm8Xzq1hHe3jUNh5SY3mAmIqZLOeVh9CRpeDY5bNTo8+9FfkqLtD37/Ii1LLoSyju4FJHVc2ky178hNZVeB898NuNM9Gt7BrDGc58CO+LDMSwVDLKVBoqQstT8yysNeFVGgwzdqwNS0Lk/6uihVb7kmo4gdcy7ZBx59uOYHFJxU/AEMUGAWhMIpbc6HiDVK+ZlBDioA0aqPtQT8zRpYj+UXmIMyEa7EhAABjj20+BScNGmwRLHHtDwLOQtJ7ru5Hj/EQBhrhHplEYh5qRHdKKLJOSjhWKWNnglIdxtXMg9NEl89ImpnfIJXuenKVqbkiW/tAAI0A5ySWcxMHbAxiZj23t9UdrLJwCXoWtDziLfP8fa+f+EOEuhpa/j/d5FoB0+Us6ikhRyP9z1YRF+dq9XPGi6CY=}
conda_forge_output_validation: true
