travis:
  secure:
    BINSTAR_TOKEN: N0/wu9M0bR0/h8Vv2PumwjSqHXyZUtLsZWDl6A9E/AC5x9RVn6gmBSE+XwPduuOq8k72u5JZRlbXp+6yFwTVuvoo/pTXylwcrtPHGXQa8lo32yGCzqbrt7GJ69vX7TFwM+iczieJ1GiSMimkhawuzmvjPLA7usjpfpBho2mdLA2jVkS3CxScs7uY3P5vzDyW1guFrE31u4TzDmJ1bV0sLOO0A6mWLVVgQ9UVy0GvYswTub6B0rTCY11BT6vgT+OD5aUSoZMj5bG6KufMpIRysPkVONiAwRVFpYj7HRGb2F3hXxIJv7ltt80dHC2RlUiOPJYqTbO3HBu4qQmNRLS+xWBJyRLl3rHtSXXFAXxz/GNhKzC6/3ucGthx8N4DWlYtKomTAymoW+2/TyO8SQd2wp6lYBI3nu7Swjm+2mrtGc/Ky4KnUEOmBSp1YAbdk4ZhVR2dCbrpw1T5rZdFCay0mEbBG+8f/ulrABo8fND6oorKHQlWHUa4g5xXXfN+0oG1boYoP/uxAukNIPqM8lEAByKazcVMyMgOnr66VTYP6Vvqv1xw9MLSvsUH4oxPeHGvoNMW7VSAVVTKFtGWviuYfrhvhFXZrsVtyiiEd911mTMV+ozClU07vbFgccUDbcwMUUf6B3f9s0uwOLdelOMZJvPvcz122K1Fy+ZBHHDNPp8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
