travis:
  secure:
    BINSTAR_TOKEN: o5YDUcQeZvAy1I7UYv5SZ7JJpsQYav9wAEfD/wmHRTsuPBnzHab0G8eLM/utMSc2yPUDYGL5eS5yU4/wJe5lzIaUGN4L3tyC0ekaIuX27W1+v7Olk7QdTS/qSA3Jix/XqzjnwwUSMS43nAJhugRGQLvETljhuZen6QcbCPB+gL9LgRUzBjaCdWMvoeg2wbgRnfSWtjunNKUpnNXK/q+l4je8qPXPLHBEgGdeYeHKymiH/MEutnnEZ110JZuMs8KIJGUtZ/dWImNGVe0sZq78/aDGiUGdwmWxb49hqDpPxVeGILNyxYahcFzJHNpZlFRXvbFoc/wlfXFYBAhv5R27nNR4z1shL77cOIzMhRekXiWggANgCop70KEXgPulxyPGAxFM+/2hohVmyNhm3ITaKZPOvZJAB64FVn7UmabHu/mz78eMFcz/x3eRPz7ANBJYW+c6WXv1k7Hju6NDaXduuvN2lVPTroOLIYxniV+vealLgvEmq1PUltCHhxSqAyb+7CSrHIqmmAWzilxXa+C5aGSLpv7Je03ycU04qLRjpN16oCU36EjVJJjzfEd0CdSfGkuAiKhGF105Gj4DUPXoIUr8EaoJd1yLsYVDYK/thYRwpwFNBh6t8BSBI0Ka9grXusxV4/F7VRrkY8KmzEmjyk1jRkY7AOMMUCqJ+iJL2H4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
